In [1]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation
import numpy as np
import time

Using TensorFlow backend.


In [2]:
""" The TensorFlow library wasn't compiled to use FMA instructions, 
but these are available on your machine and could speed up CPU computations."""
#import this code to solve this question
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

In [3]:
model = Sequential()
model.add(Dense(units=3,input_shape=(8,),activation="relu",name="hidden"))
model.add(Dense(units=8,activation="softmax",name="output"))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden (Dense)               (None, 3)                 27        
_________________________________________________________________
output (Dense)               (None, 8)                 32        
Total params: 59
Trainable params: 59
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.compile(loss="categorical_crossentropy",optimizer="adam")

In [5]:
# create data
data = []
for i in range(8):
    l = np.zeros(8)
    l[i]=1
    data.append(l)
    
data = np.array(data)

In [6]:
t = time.clock()
model.fit(data,data,batch_size=8,epochs=2000,verbose=0)
t_cost = time.clock()-t

In [7]:
score = model.evaluate(data,data)
print(score)

8/8 [==============================] - 0s
0.0980730205774


In [8]:
result = model.predict(data)
# result = ["%.0f" % j for i in result for j in i]
result = [round(j,0) for i in result for j in i]
result = np.asarray(result).reshape(-1,8)

In [9]:
print("input:")
print(data)
print("\nOutput:")
print(result)
print()
print("time cost: {}s".format(t_cost))

input:
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]

Output:
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]

time cost: 2.0527405560948155s


In [12]:
# get weights and bias
m = model.get_weights()
m

[array([[ 1.88273191,  0.31239653, -1.21071601],
        [-1.43147922,  1.69805479,  1.26833248],
        [ 1.11096501,  0.77789211,  0.87340856],
        [-1.4311496 , -1.4342289 ,  1.27587998],
        [ 2.18535089, -1.43444145,  1.21589959],
        [-0.36031696, -1.43432808, -1.21092236],
        [-1.12525535,  1.8807404 , -1.21110296],
        [-1.43143666, -0.24755242, -1.21091926]], dtype=float32),
 array([ 1.43122518,  1.43444872,  1.21071231], dtype=float32),
 array([[ 1.76724911, -1.80225599,  0.39622104, -1.58759367,  1.26988494,
          0.0431917 , -1.34004557, -1.85072255],
        [ 0.00412912,  1.22034132,  0.27458036, -1.78269422, -2.4407618 ,
         -2.30325079,  2.46637821,  0.38133955],
        [-2.27993035,  1.38346446,  0.79464406,  2.09681749,  1.00523293,
         -1.28228021, -1.89564478, -1.54259503]], dtype=float32),
 array([-2.02892041, -2.39992738, -1.4456203 ,  0.18221156, -1.66362488,
         2.82348704, -2.42349601,  2.10408998], dtype=float32)]

In [16]:
model.save("Q3_1.h5")
from keras.models import load_model
model_test = load_model("Q3_1.h5")
model_test.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden (Dense)               (None, 3)                 27        
_________________________________________________________________
output (Dense)               (None, 8)                 32        
Total params: 59
Trainable params: 59
Non-trainable params: 0
_________________________________________________________________


In [22]:
model_l1 = Sequential()
model_l1.add(Dense(units=3,input_shape=(8,),activation="relu",name="hidden",weights=model_test.layers[0].get_weights()))
model_l1.predict(data)

array([[  3.31395721e+00,   1.74684525e+00,   0.00000000e+00],
       [  0.00000000e+00,   3.13250351e+00,   2.47904491e+00],
       [  2.54219007e+00,   2.21234083e+00,   2.08412075e+00],
       [  7.55786896e-05,   2.19821930e-04,   2.48659229e+00],
       [  3.61657619e+00,   7.27176666e-06,   2.42661190e+00],
       [  1.07090819e+00,   1.20639801e-04,   0.00000000e+00],
       [  3.05969834e-01,   3.31518912e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.18689632e+00,   0.00000000e+00]], dtype=float32)