In [327]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation
import numpy as np
import time

In [328]:
model = Sequential()
model.add(Dense(units=3,input_shape=(8,),activation="relu",name="hidden"))
model.add(Dense(units=8,activation="softmax",name="output"))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden (Dense)               (None, 3)                 27        
_________________________________________________________________
output (Dense)               (None, 8)                 32        
Total params: 59
Trainable params: 59
Non-trainable params: 0
_________________________________________________________________


In [329]:
model.compile(loss="categorical_crossentropy",optimizer="adam")

In [330]:
# create data
data = []
for i in range(8):
    l = np.zeros(8)
    l[i]=1
    data.append(l)
    
data = np.array(data)

In [331]:
t = time.clock()
model.fit(data,data,batch_size=8,epochs=2000,verbose=0)
t_cost = time.clock()-t

In [332]:
score = model.evaluate(data,data)
print(score)

8/8 [==============================] - 0s
0.284026384354


In [333]:
result = model.predict(data)
# result = ["%.0f" % j for i in result for j in i]
result = [round(j,0) for i in result for j in i]
result = np.asarray(result).reshape(-1,8)

In [334]:
print("input:")
print(data)
print("\nOutput:")
print(result)
print()
print("time cost: {}s".format(t_cost))

input:
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]

Output:
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]

time cost: 4.388615293222756s
